version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSRGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5500:5432"
    networks:
      - web
  rabbit:
    image: "rabbitmq:3.8.2-rc.1-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - web

networks:
  web:
